Resources:
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicReadWrite
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              ExposedHeaders:
                - ETag
              MaxAge: 3000